# Generated by Django 2.0 on 2019-03-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190317_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Content',
        ),
    ]
