# Generated by Django 2.0 on 2019-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190322_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='word',
            field=models.CharField(max_length=355),
        ),
    ]
