# Generated by Django 2.0 on 2019-03-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190322_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('number',)},
        ),
    ]
